#!/usr/bin/env python 

import os.path
import string, sys, traceback

try:
	from tp import netlib
except ImportError:
	sys.path.append("../")
	from tp import netlib

failed = netlib.failed

import cmd

from types import *

class PyTextClient(cmd.Cmd):
	def __init__(self, completekey='tab', stdin=None, stdout=None):
		cmd.Cmd.__init__(self, completekey, stdin, stdout)

		self.debug = 0

		# Clear the storage
		self.c=None
		self.o=None

		rc = os.path.expanduser("~")
		if rc != "~":
			rc = os.path.join(rc, ".tp")
			if not os.path.exists(rc):
				os.mkdir(rc)
		
			# Import the .pytext_history
			file = os.path.join(rc, "pytext_history")
			if os.path.exists(file):
				self.pprint("Found history file: %s" % file)
				data = open(file, "r+").read()
				
				self.history = string.split(data, "\n")[:-1]

				import readline
				for line in self.history:
					if line.startswith("#"):
						continue
					readline.add_history(line)
			else:
				self.history = []

			# Import the .pytextrc
			file = os.path.join(rc, "pytextrc")
			if os.path.exists(file):
				self.pprint("Found rc file: %s" % file)
				data = open(file, "r+").read()
				
				for line in string.split(data, "\n")[:-1]:
					if line.startswith("#"):
						continue

					self.pprint("Running line: %s" % line)
					
					self.onecmd(line)

		# Set the prompt
		self.promptset()
	
	def postloop(self):
		rc = os.path.expanduser("~")
		if rc != "~":
			rc = os.path.join(rc, ".tp")
			if not os.path.exists(rc):
				os.mkdir(rc)

			data = "\n".join(self.history)
			
			# Save the .pytext_history
			file = os.path.join(rc, "pytext_history")
			print "Writing a history: %s" % file
			open(file, "w+").write(data)
			
		cmd.Cmd.postloop(self)

	def args(self, line, function):
		line = line.strip()
		if line == "":
			arguments = []
		else:
			arguments = string.split(line, " ")

		return apply(function, arguments)

	def postcmd(self, stop, line):
		self.promptset()

		if len(line.strip()) > 0:
			self.history.append(line.strip())

		return stop

	def promptset(self):
		h = "None"
		if self.c != None:
			h = self.c.host
		u = "None"
		if self.c != None and hasattr(self.c, "username"):
			u = self.c.username
		o = "None"
		if self.o != None:
			o = self.o.name

		self.prompt = "%s@%s '%s' -> " % (u, h, o)

	def pprint(self, string):
		self.columnize([string])
	

	## Default Functions #######################
	def emptyline(self):
		pass

	def complete_default(self, text, line, begidx, endidx):
		# Only do completion if there is something to match on
		r = []
	
		# Just look at the history (dont look back more then 100)
		for h in self.history[100::-1]:
			if h.startswith(line):
				if h == line:
					continue
				r.append(h[begidx:])

		return r

	completedefault = complete_default

	## Debug Functions #########################
	def do_debug(self, args):
		"""\
Toggle debug mode.
"""
		self.debug = not self.debug
		if self.c != None:
			self.c.debug = self.debug
		
	## History Functions #######################
	def do_history(self, args):
		"""\
Print a list of commands that have been entered.
"""
		for line in self.history:
			if args == "" or line.startswith(args):
				self.pprint(line)

	## Shell Functions #########################
	def do_shell(self, args):
		"""\
Pass command to a system shell.
"""
		os.system(args)

	## Python Functions ########################
	def do_exec(self, line):
		"""\
exec *python_code_to_execute

Execute python code following the exec command.
Nothing will presist after the command executes.

For example,

-> exec print 2 + 2
4
-> exec a = []
-> exec print a
name 'a' is not defined
"""
		exec(line)
		
	def do_print(self, line):
		"""\
print object_to_print

Execute python code following the exec command. For example,

user@localhost 'The Universe' -> print 2 2
2
2
user@localhost 'The Universe' -> print self.o
<netlib.objects.ObjectExtra.Universe.Universe @ 0x4020fe0c>
"""
		for i in string.split(line):
			exec("print %s" % i)

	def do_traceback(self, line):
		"""\
traceback

Print the traceback for the last error.
"""
		import traceback, pprint
		type, val, tb = sys.exc_info()
		self.pprint(string.join(traceback.format_exception(type, val, tb), ''))

	## Exit ####################################
	def do_exit(self, line):
		"""\
exit, quit

Leave the PyText-Client.
"""
		return -1

	do_quit = do_exit
	do_EOF = do_exit

	## Connect #################################
	def do_connect(self, line):
		"""\
connect host [port]

Connect to a TP server on host, if port is not specified it
uses port 6329.
"""
		return self.args(line, self.connect)

	def connect(self, host):
		self.pprint("Connecting to %s ... \n" % (host,))
		
		self.c = netlib.Connection(host, debug=self.debug)
		if not self.c.connect():
			self.c = None
			self.o = None
			self.pprint("Could not connect to the server. \n")
		else:
			self.o = None
			self.pprint("Connected. \n")

	def complete_connect(self, text, line, begidx, endidx):
		if text == "localhost"[:len(text)]:
			return ["localhost"]
		if text == "127.0.0.1"[:len(text)]:
			return ["127.0.0.1"]
		return self.complete_default(text, line, begidx, endidx)

	## Disconnect ##############################
	def do_disconnect(self, line):
		"""\
disconnect

Disconnect from the server.
"""
		return self.args(line, self.disconnect)

	def disconnect(self):
		if self.c == None:
			self.pprint("Not connected. \n")
			return

		self.c.disconnect()
		self.c = None
		self.pprint("Disconnected. \n")
		
	## Login ###################################
	def do_login(self, line):
		"""\
login username password

Login with a username and password.
"""
		return self.args(line, self.login)

	def login(self, username, password):
		if self.c == None:
			self.pprint("Not connected. \n")
			return

		if not self.c.login(username, password):
			self.pprint("Could not login. \n")
		else:
			self.pprint("Login OK. \n")

	## Object ##################################
	def do_object(self, line):
		"""\
object id

Enter into the object so you can select.
"""
		return self.args(line, self.object)
		
	def object(self, id):
		if self.c == None:
			self.pprint("Not connected. \n")
			return

		r = self.c.get_objects(int(id))
		if not failed(r[0]):
			self.o = r[0]
		else:
			self.pprint("No such object. \n")
	
	## IDs #####################################
	def do_ids(self, line):
		"""\
ids type

Gets the ids for type.
"""
		return self.args(line, self.ids)
		
	def ids(self, id):
		if self.c == None:
			self.pprint("Not connected. \n")
			return

		r = self.c.get_object_ids()
		if not failed(r):
			self.pprint(repr(r))
		else:
			self.pprint("No such object. \n")
	
	## Board ##################################
	def do_board(self, line):
		"""\
board id

Enter into the board so you can select messages.
"""
		return self.args(line, self.board)
		
	def board(self, id):
		if self.c == None:
			self.pprint("Not connected. \n")
			return

		r = self.c.get_boards(int(id))
		if not failed(r[0]):
			self.o = r[0]
		else:
			self.pprint("No such board. \n")


	## Messages ##################################
	def do_messages(self, line):
		"""\
messages [slot]

Lists the message in the current board.
"""
		return self.args(line, self.messages)

	def messages(self, *slots):
		slots = list(slots)
		for i in range(0, len(slots)):
			slots[i] = int(slots[i])
		
		if len(slots) == 0:
			slots = range(0, self.o.number)
		
		if self.c == None:
			self.pprint("Not connected. \n")
			return
		if self.o == None:
			self.pprint("No board. \n")
			return

		messages = self.c.get_messages(self.o.id, slots)
		for message in messages:
			if not failed(message):
				self.pprint("""\

%(subject)s
-------------------------
%(body)s
""" % message.__dict__)
		
	def do_message_remove(self, line):
		"""\
message_remove [slot]

Remove an message from the current board object.
"""
		return self.args(line, self.message_remove)

	def message_remove(self, *slots):
		slots = list(slots)
		for i in range(0, len(slots)):
			slots[i] = int(slots[i])
		
		if len(slots) == 0:
			slots = range(0, self.o.number)
		
		if self.c == None:
			self.pprint("Not connected. \n")
			return
		if self.o == None:
			self.pprint("No board. \n")
			return

		r = self.c.remove_messages(self.o.id, slots)
		if type(r) == ListType:
			for i in r:
				self.pprint(str(i))
		else:
			self.pprint(str(r))

	## Add Message ###############################
	def do_message_insert(self, line):
		"""\
message_insert slot subject body

Adds a new message to the board.
"""
		return self.args(line, self.message_insert)

	def message_insert(self, slot, type, *args):
		slot = int(slot)
		args = [int(x) for x in args]

		if self.c == None:
			self.pprint("Not connected. \n")
			return
		if self.o == None:
			self.pprint("No object. \n")
			return

#		self.pprint(str(apply(self.c.insert_order, (self.o.id, slot, type,) + tuple(args))))

	## Show ####################################
	def do_show(self, line):
		"""\
show [name]

Displays the value of an attribute on an object.
"""
		return self.args(line, self.show)

	def show(self, name=""):
		if self.c == None:
			self.pprint("Not connected. \n")
			return
		if self.o == None:
			self.pprint("No object. \n")
			return

		if name == "":
			for name in self.o.__dict__.keys():
				if not name.startswith('_'):
					self.show(name)
		elif name == "object":
			self.pprint("%s" % self.o)
		else:
			if hasattr(self.o, name):
				self.pprint("%s: %s \n" % (name, getattr(self.o, name)))
			else:
				self.pprint("No such attribute.")
	
	## Objects #################################
	def do_objects(self, line):
		"""\
objects

Lists the objects in the current object.
"""
		return self.args(line, self.objects)

	def objects(self, id):
		pass

	## Orders ##################################
	def do_orders(self, line):
		"""\
orders [slot]

Lists the orders in the current object.
"""
		return self.args(line, self.orders)

	def orders(self, *slots):
		slots = list(slots)
		for i in range(0, len(slots)):
			slots[i] = int(slots[i])
		
		if len(slots) == 0:
			slots = range(0, self.o.order_number)
		
		if self.c == None:
			self.pprint("Not connected. \n")
			return
		if self.o == None:
			self.pprint("No object. \n")
			return

		r = self.c.get_orders(self.o.id, slots)
		if type(r) == ListType:
			for i in r:
				self.pprint(repr(i))
		else:
			self.pprint(repr(r))
		
	def do_order_remove(self, line):
		"""\
order_remove [slot]

Remove an order from the current object.
"""
		return self.args(line, self.order_remove)

	def order_remove(self, *slots):
		slots = list(slots)
		for i in range(0, len(slots)):
			slots[i] = int(slots[i])
		
		if len(slots) == 0:
			slots = range(0, self.o.order_number)
		
		if self.c == None:
			self.pprint("Not connected. \n")
			return
		if self.o == None:
			self.pprint("No object. \n")
			return

		r = self.c.remove_orders(self.o.id, slots)
		if type(r) == ListType:
			for i in r:
				self.pprint(str(i))
		else:
			self.pprint(str(r))

	## Add Order ###############################
	def do_order_insert(self, line):
		"""\
order_insert slot type args

order_insert 1 NOp 23
order_insert -1 Move 2 6 9

Inserts a order onto the current object.
"""
		return self.args(line, self.order_insert)

	def order_insert(self, slot, type, *args):
		slot = int(slot)
		args = [int(x) for x in args]

		if type.lower() == 'nop':
			type = 0
			args[0] = int(args[0])
		elif type.lower() == 'move':
			type = 1
			args[0] = int(args[0])
			args[1] = int(args[1])
			args[2] = int(args[2])

		if self.c == None:
			self.pprint("Not connected. \n")
			return
		if self.o == None:
			self.pprint("No object. \n")
			return

		self.pprint(str(apply(self.c.insert_order, (self.o.id, slot, type,) + tuple(args))))

	## Time Stuff ##############################
	def do_time(self, line):
		"""\
time

Returns the time till end of turn
"""
		return self.args(line, self.time)

	def time(self):
		if self.c == None:
			self.pprint("Not connected. \n")
			return

		r = self.c.time()
		if r[0]:
			sh = 60*60
			sm = 60
			
			hour = int(r[1]/sh)
			min = int((r[1]-hour*sh)/sm)
			sec = r[1]-hour*sh-min*sm

			self.pprint("Turn ends: %i hours %i min %i seconds." % (hour, min, sec))
		else:
			self.pprint("Turn has ended.")
			
	##  Ping Stuff ##############################
	def do_ping(self, line):
		"""\
ping 

Pings the server.
"""
		return self.args(line, self.ping)

	def ping(self):
		if self.c == None:
			self.pprint("Not connected. \n")
			return

		r = self.c.ping()

	## Category ##################################
	def do_category(self, line):
		"""\
category id

Get the description for a category.
"""
		return self.args(line, self.category)
		
	def category(self, id):
		if self.c == None:
			self.pprint("Not connected. \n")
			return

		r = self.c.get_categories(int(id))
		if not failed(r[0]):
			self.pprint("ID: " + str(r[0].id))
			self.pprint("Name: " + r[0].name)
			self.pprint("Desc: " + r[0].description)
		else:
			self.pprint("No such category. \n")
		
	## Component ##################################
	def do_component(self, line):
		"""\
component id

Get the description for a component.
"""
		return self.args(line, self.component)
		
	def component(self, id):
		if self.c == None:
			self.pprint("Not connected. \n")
			return

		r = self.c.get_components(int(id))
		if not failed(r[0]):
			self.pprint("ID: " + str(r[0].id))
			self.pprint("Time: " + str(r[0].modify_time))

			categories = []
			for category in self.c.get_categories(r[0].categories):
				if not failed(category):
					categories.append((category.name, category.description))
				else:
					categories.append("Failed to get category.")
			
			self.pprint("Categories: " + str(categories))
			self.pprint("Name: " + str(r[0].name))
			self.pprint("Description: " + str(r[0].description))
			self.pprint("Requirements: " + str(r[0].requirements))
			
			properties = []
			for property_id, property_value in r[0].properties:
				property = self.c.get_properties(property_id)
				if not failed(property[0]):
					properties.append((property[0].name, property_value))
				else:
					properties.append("Failed to get property.")
			self.pprint("Properties: " + str(properties))
		else:
			self.pprint("No such component. \n")

	## Design ##################################
	def do_design(self, line):
		"""\
design id

Get the description for a design.
"""
		return self.args(line, self.design)
		
	def design(self, id):
		if self.c == None:
			self.pprint("Not connected. \n")
			return

		r = self.c.get_designs(int(id))
		if not failed(r[0]):
			self.pprint("ID: " + str(r[0].id))
			self.pprint("Time: " + str(r[0].modify_time))

			categories = []
			for category in self.c.get_categories(r[0].categories):
				if not failed(category):
					categories.append((category.name, category.description))
				else:
					categories.append("Failure to get category.")
			
			self.pprint("Categories: " + str(categories))
			self.pprint("Name: " + str(r[0].name))
			self.pprint("Description: " + str(r[0].description))
			self.pprint("Used: " + str(r[0].used))
			self.pprint("Owner: " + str(r[0].owner))
			self.pprint("Feedback: " + str(r[0].feedback))
		
			components = []
			for component_id, number in r[0].components:
				component = self.c.get_components(component_id)
				if not failed(component):
					components.append((component[0].name, number))
				else:
					components.append("Failure to get component.")
			self.pprint("Components: " + str(components))

			properties = []
			for property_id, property_display in r[0].properties:
				property = self.c.get_properties(property_id)
				if not failed(property):
					properties.append((property[0].name, property_display))
				else:
					properties.append("Failure to get property.")
			self.pprint("Properties: " + str(properties))
		else:
			self.pprint("No such design. \n")

def main():
	m = PyTextClient()
	while True:
		try:
			m.cmdloop()
		except SystemExit, e:
			break
		except Exception, e:
			type, val, tb = sys.exc_info()
			print ''.join(traceback.format_exception(type, val, tb))
			continue
		else:
			return

if __name__ == "__main__":
	main()

